kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: iscalecc-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: iscalecc-prometheus-exporter
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP